# Generated by Django 4.0.6 on 2022-07-31 23:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('starters', 'Starters'), ('mains', 'Mains'), ('sides', 'Sides'), ('drinks', 'Drinks'), ('desserts', 'Desserts')], default='mains', max_length=25)),
                ('sku', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, choices=[('fl oz', 'Fluid Ounce'), ('ml', 'Milliliters'), ('g', 'Grams'), ('mg', 'Milligrams'), ('mcg', 'Micrograms')], default='', max_length=11)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Nutrient',
                'verbose_name_plural': 'Nutrients',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Serving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_container', models.FloatField()),
                ('size', models.FloatField()),
                ('unit', models.CharField(blank=True, choices=[('fl oz', 'Fluid Ounce'), ('ml', 'Milliliters'), ('g', 'Grams'), ('mg', 'Milligrams'), ('mcg', 'Micrograms')], default='', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('dv_percentage', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='meals.meal')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_facts', to='meals.nutrient')),
            ],
            options={
                'verbose_name': 'Nutrition Fact',
                'verbose_name_plural': 'Nutrition Facts',
                'ordering': ['nutrient__order'],
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='serving_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='meals.serving'),
        ),
        migrations.AddConstraint(
            model_name='nutritionfact',
            constraint=models.UniqueConstraint(fields=('meal', 'nutrient'), name='nutrition_fact_unique_together_meal_nutrient'),
        ),
    ]
